/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    screens: {
      xs: {
        min: '0px',
      },
      sm: {
        min: '576px',
      },
      md: {
        min: '768px',
      },
      lg: {
        min: '992px',
      },
      xl: {
        min: '1200px',
      },
      xxl: {
        min: '1400px',
      },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        xs: '1rem',
        sm: '1rem',
        md: '2rem',
        lg: '2rem',
        xl: '2rem',
        xxl: '2rem',
      },
      screens: {
        xs: '100%',
        sm: '540px',
        md: '720px',
        lg: '960px',
        xl: '1140px',
        xxl: '1320px',
      },
    },
    fontWeight: {},
    fontFamily: {},
    colors: {
      background: {
        DEFAULT: '#fff',
        soft: '#F7F7F7',
        brand: '#C8102E',
        cta: '#C8102E',
        ctaHover: '#900837',
        inverse: '#303030',
        inverseHover: '#424242',
        contrast: '#fff',
        contrastHover: '#F0F0F0',
        disabled: '#D3D3D3',
        negative: '#BF165D',
      },
      content: {
        DEFAULT: '#262626',
        soft: '#6F6F6F',
        brand: '#C8102E',
        cta: '#C8102E',
        ctaHover: '#900837',
        onBrand: '#fff',
        onCta: '#fff',
        inverse: '#fff',
        inverseHover: '#F0F0F0',
        onContrast: '#C8102E',
        disabled: '#A8A8A8',
        negative: '#BF165D',
      },
      border: {
        DEFAULT: '#595959',
        soft: '#D3D3D3',
        brand: '#C8102E',
        cta: '#C8102E',
        ctaHover: '#900837',
        inverse: '#fff',
        inverseHover: '#F0F0F0',
        disabled: '#A8A8A8',
        negative: '#BF165D',
        focus: '#006E9E',
      },
      black: '#000',
      white: '#fff',
      transparent: '#ffffff03',
      primary: {
        100: '#FCD7CD',
        200: '#F9A89D',
        300: '#EE6E6A',
        400: '#DE444F',
        500: '#C8102E',
        600: '#C2331B',
        700: '#900837',
        800: '#740536',
        900: '#600335',
      },
      secondary: {
        100: '#FCF4C9',
        200: '#F9E895',
        300: '#EED25F',
        400: '#DEB937',
        500: '#C99700',
        600: '#AC7D00',
        700: '#906500',
        800: '#744E00',
        900: '#603E00',
      },
      mono: {
        100: '#F7F7F7',
        200: '#F0F0F0',
        300: '#D3D3D3',
        400: '#A8A8A8',
        500: '#6F6F6F',
        600: '#595959',
        700: '#424242',
        800: '#303030',
        900: '#262626',
      },
      focus: {
        100: '#C8F8FA',
        200: '#93EBF5',
        300: '#5ACAE1',
        400: '#31A1C4',
        500: '#006E9E',
        600: '#005587',
        700: '#004071',
        800: '#002D5B',
        900: '#00204B',
      },
      negative: {
        100: '#FBCFD0',
        200: '#F8A0AB',
        300: '#EB6E8A',
        400: '#D84876',
        500: '#BF165D',
        600: '#A4105D',
        700: '#890B59',
        800: '#6E0751',
        900: '#5B044B',
      },
    },
    spacing: {
      0: '0px',
      nano: '0.25rem',
      xxsmall: '0.375rem',
      xsmall: '0.5rem',
      small: '0.75rem',
      medium: '1rem',
      large: '1.5rem',
      xlarge: '2rem',
      xxlarge: '2.5rem',
      huge: '3rem',
      xhuge: '3.5rem',
      xxhuge: '4rem',
      giant: '5rem',
      xgiant: '7.5rem',
      xxgiant: '10rem',
    },
    borderRadius: {
      DEFAULT: 0,
      pill: '1000px',
      none: 0,
      small: '4px',
      medium: '8px',
      large: '16px',
    },
    borderWidth: {
      DEFAULT: '1px',
      focus: '2px',
      none: 0,
      hairline: '1px',
      thin: '2px',
      thick: '4px',
    },
    fontSize: {
      xxnano: '0.75rem',
      xnano: '0.875rem',
      nano: '1rem',
      xxsmall: '1.125rem',
      xsmall: '1.25rem',
      small: '1.5rem',
      medium: '1.75rem',
      large: '2rem',
      xlarge: '2.5rem',
      xxlarge: '3rem',
      huge: '3.5rem',
      xhuge: '4rem',
      xxhuge: '4.5rem',
      giant: '5rem',
      xgiant: '5.5rem',
      xxgiant: '6rem',
      display: '7rem',
      xdisplay: '9.25rem',
    },
    lineHeight: {
      xloose: '200%',
      loose: '175%',
      normal: '150%',
      tight: '120%',
      xtight: '100%',
    },
    letterSpacing: {
      xloose: '0.04px',
      loose: '0.02px',
      normal: 0,
      tight: '-0.02px',
      xtight: '-0.04px',
    },
    boxShadow: {
      small: '0px 4px 8px 0px #00000014',
      medium: '0px 8px 24px 0px #00000029',
      large: '0px 16px 32px 0px #00000029',
      xlarge: '0px 16px 48px 0px #00000029',
    },
    dropShadow: {
      small: '0px 4px 8px #00000014',
      medium: '0px 8px 24px #00000029',
      large: '0px 16px 32px #00000029',
      xlarge: '0px 16px 48px #00000029',
    },
    height: {
      0: '0px',
      xxnano: '0.0625rem',
      xnano: '0.125rem',
      nano: '0.25rem',
      xxsmall: '0.375rem',
      xsmall: '0.5rem',
      small: '0.75rem',
      medium: '1rem',
      large: '1.5rem',
      xlarge: '2rem',
      xxlarge: '2.5rem',
      huge: '3rem',
      xhuge: '3.5rem',
      xxhuge: '4rem',
      giant: '5rem',
      xgiant: '7.5rem',
      xxgiant: '10rem',
      auto: 'auto',
      '1/2': '50%',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      '10vh': '10vh',
      '20vh': '20vh',
      '30vh': '30vh',
      '40vh': '40vh',
      '50vh': '50vh',
      '60vh': '60vh',
      '70vh': '70vh',
      '80vh': '80vh',
      '90vh': '90vh',
      screen: '100vh',
    },
    maxHeight: {
      0: '0px',
      xxnano: '0.0625rem',
      xnano: '0.125rem',
      nano: '0.25rem',
      xxsmall: '0.375rem',
      xsmall: '0.5rem',
      small: '0.75rem',
      medium: '1rem',
      large: '1.5rem',
      xlarge: '2rem',
      xxlarge: '2.5rem',
      huge: '3rem',
      xhuge: '3.5rem',
      xxhuge: '4rem',
      giant: '5rem',
      xgiant: '7.5rem',
      xxgiant: '10rem',
      auto: 'auto',
      '1/2': '50%',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      '10vh': '10vh',
      '20vh': '20vh',
      '30vh': '30vh',
      '40vh': '40vh',
      '50vh': '50vh',
      '60vh': '60vh',
      '70vh': '70vh',
      '80vh': '80vh',
      '90vh': '90vh',
      screen: '100vh',
    },
    minHeight: {
      0: '0px',
      xxnano: '0.0625rem',
      xnano: '0.125rem',
      nano: '0.25rem',
      xxsmall: '0.375rem',
      xsmall: '0.5rem',
      small: '0.75rem',
      medium: '1rem',
      large: '1.5rem',
      xlarge: '2rem',
      xxlarge: '2.5rem',
      huge: '3rem',
      xhuge: '3.5rem',
      xxhuge: '4rem',
      giant: '5rem',
      xgiant: '7.5rem',
      xxgiant: '10rem',
      auto: 'auto',
      '1/2': '50%',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      '10vh': '10vh',
      '20vh': '20vh',
      '30vh': '30vh',
      '40vh': '40vh',
      '50vh': '50vh',
      '60vh': '60vh',
      '70vh': '70vh',
      '80vh': '80vh',
      '90vh': '90vh',
      screen: '100vh',
    },
    width: {
      0: '0px',
      xxnano: '0.0625rem',
      xnano: '0.125rem',
      nano: '0.25rem',
      xxsmall: '0.375rem',
      xsmall: '0.5rem',
      small: '0.75rem',
      medium: '1rem',
      large: '1.5rem',
      xlarge: '2rem',
      xxlarge: '2.5rem',
      huge: '3rem',
      xhuge: '3.5rem',
      xxhuge: '4rem',
      giant: '5rem',
      xgiant: '7.5rem',
      xxgiant: '10rem',
      auto: 'auto',
      '1/2': '50%',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      '10vw': '10vw',
      '20vw': '20vw',
      '30vw': '30vw',
      '40vw': '40vw',
      '50vw': '50vw',
      '60vw': '60vw',
      '70vw': '70vw',
      '80vw': '80vw',
      '90vw': '90vw',
      screen: '100vw',
    },
    maxWidth: {
      0: '0px',
      xxnano: '0.0625rem',
      xnano: '0.125rem',
      nano: '0.25rem',
      xxsmall: '0.375rem',
      xsmall: '0.5rem',
      small: '0.75rem',
      medium: '1rem',
      large: '1.5rem',
      xlarge: '2rem',
      xxlarge: '2.5rem',
      huge: '3rem',
      xhuge: '3.5rem',
      xxhuge: '4rem',
      giant: '5rem',
      xgiant: '7.5rem',
      xxgiant: '10rem',
      auto: 'auto',
      '1/2': '50%',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      '10vw': '10vw',
      '20vw': '20vw',
      '30vw': '30vw',
      '40vw': '40vw',
      '50vw': '50vw',
      '60vw': '60vw',
      '70vw': '70vw',
      '80vw': '80vw',
      '90vw': '90vw',
      screen: '100vw',
    },
    minWidth: {
      0: '0px',
      xxnano: '0.0625rem',
      xnano: '0.125rem',
      nano: '0.25rem',
      xxsmall: '0.375rem',
      xsmall: '0.5rem',
      small: '0.75rem',
      medium: '1rem',
      large: '1.5rem',
      xlarge: '2rem',
      xxlarge: '2.5rem',
      huge: '3rem',
      xhuge: '3.5rem',
      xxhuge: '4rem',
      giant: '5rem',
      xgiant: '7.5rem',
      xxgiant: '10rem',
      auto: 'auto',
      '1/2': '50%',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      '10vw': '10vw',
      '20vw': '20vw',
      '30vw': '30vw',
      '40vw': '40vw',
      '50vw': '50vw',
      '60vw': '60vw',
      '70vw': '70vw',
      '80vw': '80vw',
      '90vw': '90vw',
      screen: '100vw',
    },
  },
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/forms'),
    require('tailwindcss/plugin')(function ({ addComponents }) {
      addComponents({
        '.button': {
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          gap: '0.25rem',
          fontFamily: 'Amble, Arial',
          fontWeight: '700',
          lineHeight: '100%',
          fontSize: '1rem',
          textDecoration: 'none',
          letterSpacing: 0,
          transition: 'all 300ms ease',
          '&:focus': {
            boxShadow: '0 0 0 0.25rem #006e9e80',
          },
        },
        '.button-size-small': {
          height: '2.5rem',
          minWidth: '2.5rem',
          paddingLeft: '0.75rem',
          paddingRight: '0.75rem',
        },
        '.button-size-medium': {
          height: '3rem',
          minWidth: '3rem',
          paddingLeft: '1rem',
          paddingRight: '1rem',
        },
        '.button-size-large': {
          height: '3.5rem',
          minWidth: '3.5rem',
          paddingLeft: '1.5rem',
          paddingRight: '1.5rem',
        },
        '.button-variant-primary-main': {
          color: '#fff',
          backgroundColor: '#C8102E',
          '&:hover': {
            color: '#fff',
            backgroundColor: '#900837',
          },
          '&:focus': {
            outline: '2px solid #006E9E',
            outlineOffset: '-2px',
          },
          '&:disabled': {
            color: '#A8A8A8 !important',
            backgroundColor: '#D3D3D3 !important',
          },
        },
        '.button-variant-primary-contrast': {
          color: '#C8102E',
          backgroundColor: '#fff',
          '&:hover': {
            color: '#C8102E',
            backgroundColor: '#F0F0F0',
          },
          '&:focus': {
            outline: '2px solid #006E9E',
            outlineOffset: '-2px',
          },
          '&:disabled': {
            color: '#A8A8A8 !important',
            backgroundColor: '#D3D3D3 !important',
          },
        },
        '.button-variant-secondary-main': {
          color: '#C8102E',
          outline: '1px solid #C8102E',
          outlineOffset: '-1px',
          '&:hover': {
            color: '#900837',
            outline: '1px solid #900837',
            outlineOffset: '-1px',
          },
          '&:focus': {
            outline: '2px solid #006E9E',
            outlineOffset: '-2px',
          },
          '&:disabled': {
            color: '#A8A8A8 !important',
            outline: '1px solid #A8A8A8 !important',
            outlineOffset: '-1px !important',
          },
        },
        '.button-variant-secondary-contrast': {
          color: '#fff',
          outline: '1px solid #fff',
          outlineOffset: '-1px',
          '&:hover': {
            color: '#F0F0F0',
            outline: '1px solid #F0F0F0',
            outlineOffset: '-1px',
          },
          '&:focus': {
            outline: '2px solid #006E9E',
            outlineOffset: '-2px',
          },
          '&:disabled': {
            color: '#A8A8A8 !important',
            outline: ' !important',
            outlineOffset: '-undefined !important',
          },
        },
        '.button-variant-ghost-main': {
          color: '#C8102E',
          '&:hover': {
            color: '#900837',
          },
          '&:focus': {
            outline: '2px solid #006E9E',
            outlineOffset: '-2px',
          },
          '&:disabled': {
            color: '#A8A8A8 !important',
          },
        },
        '.button-variant-ghost-contrast': {
          color: '#fff',
          '&:hover': {
            color: '#F0F0F0',
          },
          '&:focus': {
            outline: '2px solid #006E9E',
            outlineOffset: '-2px',
          },
          '&:disabled': {
            color: '#A8A8A8 !important',
          },
        },
        '.typography-display-color-main': {
          color: '#C8102E',
        },
        '.typography-display-color-contrast': {
          color: '#fff',
        },
        '.typography-display-size-small-default': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '3.5rem',
          letterSpacing: '-0.02px',
        },
        '.typography-display-size-small-responsive': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '4.5rem',
          letterSpacing: '-0.02px',
        },
        '.typography-display-size-medium-default': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '4rem',
          letterSpacing: '-0.02px',
        },
        '.typography-display-size-medium-responsive': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '5rem',
          letterSpacing: '-0.02px',
        },
        '.typography-display-size-large-default': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '4.5rem',
          letterSpacing: '-0.02px',
        },
        '.typography-display-size-large-responsive': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '5.5rem',
          letterSpacing: '-0.02px',
        },
        '.typography-overline': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '1rem',
          letterSpacing: '0.04px',
        },
        '.typography-overline-color-main': {
          color: '#6F6F6F',
        },
        '.typography-overline-color-contrast': {
          color: '#fff',
        },
        '.typography-label': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '0.875rem',
          letterSpacing: 0,
        },
        '.typography-label-color-main': {
          color: '#C8102E',
        },
        '.typography-label-color-contrast': {
          color: '#fff',
        },
        '.typography-paragraph-color-main': {
          color: '#262626',
        },
        '.typography-paragraph-color-contrast': {
          color: '#fff',
        },
        '.typography-paragraph-size-small': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
          lineHeight: '150%',
          textTransform: 'none',
          fontSize: '0.875rem',
          letterSpacing: 0,
        },
        '.typography-paragraph-size-medium': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
          lineHeight: '150%',
          textTransform: 'none',
          fontSize: '1rem',
          letterSpacing: 0,
        },
        '.typography-paragraph-size-large': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
          lineHeight: '150%',
          textTransform: 'none',
          fontSize: '1.125rem',
          letterSpacing: 0,
        },
        '.typography-subtitle-color-main': {
          color: '#6F6F6F',
        },
        '.typography-subtitle-color-contrast': {
          color: '#fff',
        },
        '.typography-subtitle-size-medium-default': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
          lineHeight: '120%',
          textTransform: 'none',
          fontSize: '1.25rem',
          letterSpacing: 0,
        },
        '.typography-subtitle-size-medium-responsive': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
          lineHeight: '120%',
          textTransform: 'none',
          fontSize: '1.5rem',
          letterSpacing: 0,
        },
        '.typography-subtitle-size-large-default': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
          lineHeight: '120%',
          textTransform: 'none',
          fontSize: '1.5rem',
          letterSpacing: 0,
        },
        '.typography-subtitle-size-large-responsive': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
          lineHeight: '120%',
          textTransform: 'none',
          fontSize: '1.75rem',
          letterSpacing: 0,
        },
        '.typography-heading-color-main': {
          color: '#C8102E',
        },
        '.typography-heading-color-contrast': {
          color: '#fff',
        },
        '.typography-heading-size-xsmall-default': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '1rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-xsmall-responsive': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '1rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-small-default': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '1.5rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-small-responsive': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '1.5rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-medium-default': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '1.75rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-medium-responsive': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '2rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-large-default': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '2.5rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-large-responsive': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '3rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-xlarge-default': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '3rem',
          letterSpacing: '-0.02px',
        },
        '.typography-heading-size-xlarge-responsive': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
          lineHeight: '100%',
          textTransform: 'uppercase',
          fontSize: '3.5rem',
          letterSpacing: '-0.02px',
        },
        '.icon-size-small': {
          minWidth: '1rem',
          maxWidth: '1rem',
          minHeight: '1rem',
          maxHeight: '1rem',
        },
        '.icon-size-medium': {
          minWidth: '1.5rem',
          maxWidth: '1.5rem',
          minHeight: '1.5rem',
          maxHeight: '1.5rem',
        },
        '.icon-size-large': {
          minWidth: '2rem',
          maxWidth: '2rem',
          minHeight: '2rem',
          maxHeight: '2rem',
        },
        '.divider': {
          width: '100%',
          display: 'flex',
          alignItems: 'center',
          color: '#6F6F6F',
          minHeight: '1px',
          '&::before': {
            content: '""',
            width: '100%',
            borderTop: '1px solid #D3D3D3',
          },
          '&::after': {
            content: '""',
            width: '100%',
            borderTop: '1px solid #D3D3D3',
          },
        },
        '.divider-overline': {
          marginLeft: '10px',
          marginRight: '10px',
        },
        '.overlay': {
          position: 'relative',
          '&::after': {
            content: '""',
            position: 'absolute',
            width: '100%',
            height: '100%',
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
            backgroundColor: '#0000003d',
          },
        },
        '.overlay-blur': {
          '&::after': {
            backdropFilter: 'blur(16px)',
          },
        },
        '.link': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
          lineHeight: '150%',
          textTransform: 'none',
          fontSize: '1rem',
          letterSpacing: 0,
          textDecoration: 'none',
          backgroundRepeat: 'no-repeat',
          backgroundPosition: 'left bottom',
          transition: 'all 300ms ease',
          backgroundImage: 'none',
          backgroundSize: '0% 0.0625rem',
          '&:hover, &:focus': {
            backgroundSize: '100% 0.0625rem',
          },
          '&:focus': {
            boxShadow: '0 0 0 0.25rem #006e9e80',
            outline: '2px solid #006E9E',
          },
        },
        '.link-color-main': {
          color: '#C8102E',
          '&:hover, &:focus': {
            color: '#900837',
            backgroundImage:
              'linear-gradient(to right,#900837 50%,#900837 50%)',
          },
        },
        '.link-color-contrast': {
          color: '#fff',
          '&:hover, &:focus': {
            color: '#F0F0F0',
            backgroundImage:
              'linear-gradient(to right,#F0F0F0 50%,#F0F0F0 50%)',
          },
        },
        '.progress-bar': {
          height: '0.25rem',
        },
        '.progress-bar-color-main': {
          backgroundColor: '#00000029',
        },
        '.progress-bar-color-contrast': {
          backgroundColor: '#ffffff52',
        },
        '.progress-bar-indicator': {
          height: '0.25rem',
        },
        '.progress-bar-indicator-color-main': {
          backgroundColor: '#C8102E',
        },
        '.progress-bar-indicator-color-contrast': {
          backgroundColor: '#fff',
        },
        '.pagination-timed': {
          gap: '1rem',
        },
        '.pagination-timed-control': {
          gap: '1rem',
        },
        '.pagination-timed-pages-default': {
          gap: '0.5rem',
        },
        '.pagination-timed-pages-responsive': {
          gap: '1.5rem',
        },
        '.card': {
          borderRadius: 0,
          border: '1px solid #D3D3D3',
          boxShadow: '',
        },
        '.card-media': {
          padding: '0 0',
          backgroundColor: '#ffffff03',
        },
        '.card-body': {
          padding: '1.5rem 1rem 1rem 1rem',
          gap: '0.75rem',
          backgroundColor: '#ffffff03',
        },
        '.card-overline': {
          padding: '0.5rem 1rem',
          backgroundColor: '#C8102E',
        },
        '.card-footer': {
          padding: '0 1rem 0.5rem 1rem',
          backgroundColor: '#ffffff03',
        },
        '.accordion': {
          borderBottom: '1px solid #D3D3D3',
          '&:hover': {
            '> .accordion-header': {
              backgroundColor: '#F7F7F7',
            },
          },
        },
        '.accordion > summary': {
          '.accordion-header-icon-remove': {
            display: 'none !important',
          },
          '.accordion-header-icon-add': {
            display: 'block !important',
          },
        },
        '.accordion[open] > summary': {
          '.accordion-header-icon-remove': {
            display: 'block !important',
          },
          '.accordion-header-icon-add': {
            display: 'none !important',
          },
        },
        '.accordion-header': {
          padding: '0.75rem 1rem',
          backgroundColor: '#ffffff03',
          transition: 'all 300ms ease',
          '&:focus': {
            boxShadow: '0 0 0 0.25rem #006e9e80',
            outline: '2px solid #006E9E',
            outlineOffset: '-2px',
          },
        },
        '.accordion-header-icon': {
          color: '#6F6F6F',
        },
        '.accordion-content-default': {
          padding: '0.5rem 3rem 1.5rem 1rem',
        },
        '.accordion-content-responsive': {
          padding: '0.5rem 5rem 1.5rem 1rem',
        },
        '.input-container': {
          gap: '0.375rem',
          '.input-container-label': {
            color: '#C8102E',
            '&.input-container-label-disabled': {
              color: '#A8A8A8',
            },
          },
          '.input-container-counter': {
            color: '#6F6F6F',
            '&.input-container-counter-disabled': {
              color: '#A8A8A8',
            },
          },
          '.input-container-field': {
            color: '#262626',
            height: '3rem',
            padding: '0.75rem 1rem',
            borderRadius: 0,
            outline: '1px solid #D3D3D3',
            outlineOffset: '-1px',
            backgroundColor: '#fff',
            '&:disabled': {
              color: '#A8A8A8',
              outline: '1px solid #A8A8A8',
              outlineOffset: '-1px',
              backgroundColor: '#D3D3D3',
            },
            '&:focus': {
              outline: '2px solid #006E9E',
              outlineOffset: '-2px',
              boxShadow: '0 0 0 0.25rem #006e9e80',
            },
            '&::placeholder': {
              color: '#6F6F6F',
            },
            '&.input-container-field-error': {
              color: '#BF165D',
              '&:focus': {
                outline: '2px solid #BF165D',
                outlineOffset: '-2px',
                boxShadow: '0 0 0 0.25rem #bf165d80',
              },
            },
          },
          '.input-container-textarea': {
            color: '#262626',
            padding: '0.75rem 1rem',
            borderRadius: 0,
            outline: '1px solid #D3D3D3',
            outlineOffset: '-1px',
            backgroundColor: '#fff',
            '&:disabled': {
              color: '#A8A8A8',
              outline: '1px solid #A8A8A8',
              outlineOffset: '-1px',
              backgroundColor: '#D3D3D3',
            },
            '&:focus': {
              outline: '2px solid #006E9E',
              outlineOffset: '-2px',
              boxShadow: '0 0 0 0.25rem #006e9e80',
            },
            '&::placeholder': {
              color: '#6F6F6F',
            },
            '&.input-container-textarea-error': {
              color: '#BF165D',
              '&:focus': {
                outline: '2px solid #BF165D',
                outlineOffset: '-2px',
                boxShadow: '0 0 0 0.25rem #bf165d80',
              },
            },
          },
          '.input-container-select': {
            height: '3rem',
            color: '#262626',
            padding: '0.75rem 1rem',
            borderRadius: 0,
            outline: '1px solid #D3D3D3',
            outlineOffset: '-1px',
            backgroundColor: '#fff',
            '&.input-container-select-disabled': {
              color: '#A8A8A8',
              outline: '1px solid #A8A8A8',
              outlineOffset: '-1px',
              backgroundColor: '#D3D3D3',
            },
            '&.input-container-select-focus': {
              outline: '2px solid #006E9E',
              outlineOffset: '-2px',
              boxShadow: '0 0 0 0.25rem #006e9e80',
            },
            '&.input-container-select-error': {
              '&.input-container-select-focus': {
                outline: '2px solid #BF165D',
                outlineOffset: '-2px',
                boxShadow: '0 0 0 0.25rem #bf165d80',
              },
              '.input-container-select-value': {
                '.input-container-select-value-single': {
                  color: '#BF165D !important',
                },
              },
            },
            '.input-container-select-value': {
              '.input-container-select-value-placeholder': {
                color: '#6F6F6F',
              },
              '.input-container-select-value-single': {
                color: '#262626',
              },
              '.input-container-select-value-input': {
                '> input': {
                  '&:focus': {
                    outline: '0 !important',
                    border: '0 !important',
                    boxShadow: 'none !important',
                  },
                },
              },
            },
          },
          '.input-container-checkbox': {
            '&:focus': {
              boxShadow: '0 0 0 0.25rem #006e9e80',
            },
          },
          '.input-container-radio': {
            '&:focus': {
              boxShadow: '0 0 0 0.25rem #006e9e80',
            },
          },
          '.input-container-date': {
            color: '#262626',
            height: '3rem',
            padding: '0.75rem 1rem',
            borderRadius: 0,
            outline: '1px solid #D3D3D3',
            outlineOffset: '-1px',
            backgroundColor: '#fff',
            '&:disabled': {
              color: '#A8A8A8',
              outline: '1px solid #A8A8A8',
              outlineOffset: '-1px',
              backgroundColor: '#D3D3D3',
            },
            '&:focus': {
              outline: '2px solid #006E9E',
              outlineOffset: '-2px',
              boxShadow: '0 0 0 0.25rem #006e9e80',
            },
            '&::placeholder': {
              color: '#6F6F6F',
            },
            '&.input-container-date-error': {
              color: '#BF165D',
              '&:focus': {
                outline: '2px solid #BF165D',
                outlineOffset: '-2px',
                boxShadow: '0 0 0 0.25rem #bf165d80',
              },
            },
          },
          '.input-container-mask': {
            color: '#262626',
            height: '3rem',
            padding: '0.75rem 1rem',
            borderRadius: 0,
            outline: '1px solid #D3D3D3',
            outlineOffset: '-1px',
            backgroundColor: '#fff',
            '&:disabled': {
              color: '#A8A8A8',
              outline: '1px solid #A8A8A8',
              outlineOffset: '-1px',
              backgroundColor: '#D3D3D3',
            },
            '&:focus': {
              outline: '2px solid #006E9E',
              outlineOffset: '-2px',
              boxShadow: '0 0 0 0.25rem #006e9e80',
            },
            '&::placeholder': {
              color: '#6F6F6F',
            },
            '&.input-container-mask-error': {
              color: '#BF165D',
              '&:focus': {
                outline: '2px solid #BF165D',
                outlineOffset: '-2px',
                boxShadow: '0 0 0 0.25rem #bf165d80',
              },
            },
          },
          '.input-container-file': {
            color: '#fff',
            backgroundColor: '#C8102E',
            height: '2.5rem',
            minWidth: '2.5rem',
            paddingLeft: '0.75rem',
            paddingRight: '0.75rem',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            gap: '0.25rem',
            fontFamily: 'Amble, Arial',
            fontWeight: '700',
            lineHeight: '100%',
            fontSize: '1rem',
            textDecoration: 'none',
            letterSpacing: 0,
            transition: 'all 300ms ease',
            '&.input-container-file-disabled': {
              '&, &:hover': {
                color: '#A8A8A8',
                backgroundColor: '#D3D3D3',
              },
            },
            '&:hover': {
              color: '#fff',
              backgroundColor: '#900837',
            },
            '&:focus': {
              outline: '2px solid #006E9E',
              outlineOffset: '-2px',
              boxShadow: '0 0 0 0.25rem #006e9e80',
            },
          },
          '.input-container-addons': {
            gap: '0.375rem',
          },
          '.input-container-helper': {
            color: '#6F6F6F',
          },
          '.input-container-helper-error': {
            color: '#BF165D',
          },
          '.input-container-error-icon': {
            color: '#BF165D',
          },
        },
        '.font-body-regular': {
          fontFamily: 'Amble, Arial',
          fontWeight: '400',
        },
        '.font-body-bold': {
          fontFamily: 'Amble, Arial',
          fontWeight: '700',
        },
        '.font-heading-regular': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '400',
        },
        '.font-heading-bold': {
          fontFamily: 'Mohave, Impact',
          fontWeight: '600',
        },
        '.social-share-button-facebook': {
          backgroundColor: '#1877F2',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#0c5eca',
            color: '#fff',
          },
        },
        '.social-share-button-twitter': {
          backgroundColor: '#1D9BF0',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#0E80CE',
            color: '#fff',
          },
        },
        '.social-share-button-google': {
          backgroundColor: '#fff',
          color: '#262626',
          '&:hover': {
            backgroundColor: '#F7F7F7',
            color: '#262626',
          },
        },
        '.social-share-button-twitch': {
          backgroundColor: '#6441A4',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#4E3380',
            color: '#fff',
          },
        },
        '.social-share-button-whatsapp': {
          backgroundColor: '#25D366',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#1EA952',
            color: '#fff',
          },
        },
        '.social-login-button-facebook': {
          backgroundColor: '#1877F2',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#0c5eca',
            color: '#fff',
          },
        },
        '.social-login-button-twitter': {
          backgroundColor: '#1D9BF0',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#0E80CE',
            color: '#fff',
          },
        },
        '.social-login-button-google': {
          backgroundColor: '#fff',
          color: '#262626',
          border: '1px solid #D0D0CE',
          '&:hover': {
            backgroundColor: '#F7F7F7',
            color: '#262626',
          },
        },
        '.social-login-button-twitch': {
          backgroundColor: '#6441A4',
          color: '#fff',
          '&:hover': {
            backgroundColor: '#4E3380',
            color: '#fff',
          },
        },
      })
    }),
  ],
}
